# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca6c28a5e07118ca676abd0c0b1f34856661a9b71995b6d65b058c7363c14dd6439ca95bc2ba55480c71f4e3e1d35c888bb91b8ce194ddb6eea173b00bf12936

test:
  secret_key_base: 7513a88221f51662e7c3927f08b8f0fd97f9fe2434a3e93c4569d8ffcf679ad85acfbbd9b4b1d3953d194d525f951bb7b4ddb12630835f0d251d453b6cb782cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
